language: groovy
jdk:
- oraclejdk7
sudo: false
branches:
  only:
  - master
before_install:
- wget -q https://raw.githubusercontent.com/GBIFes/travis-build-configuration/master/ala_common.sh
- chmod +x ala_common.sh
- source ./ala_common.sh
- ala_travis_grails_setup_env
script:
- ala_travis_grails_build
env:
  global:
  - secure: RPpKLcQThfQDVzhkPTZtEMys546hQdwEAtCPs5K4FH+a4a7gTgxwDm2glNY+pusBFGB5/zkZBhfGqHv+QlZ8JJNwKncbUY0XXzUOSt51inGjF5kV2DNdAowZLKhtztavyuQP+nlotLMAPHQhdUr5cnONJorOr9QRTcY87H3L6c1bQ0dvZdQwQ3pEM0axDH6O/7FJqChCGjzCuB0leYLLdlt6ttxV8GxAc0XvGxyBQ2GBGedYLvF7oiHxHR3pdjfZzys+I/02G3TQmUIYMTFO/fMA6kWQg39BnTOE2fWsKklftr01/5g1+zRw+Xto9m8bMLNqxdPnaZ8cAweZKABqIi/IrWsRPFrwHfs6IwBeLLZ6yhyZKtKUsK67zUXyywwB+H4RNWgsqfr+ymaO8yVlDtTZ1hBHQ4jiZ24VJM/0sB70hYW+9FOZYU5NdvY2OiKRlpu87Peh3AQoB99nEUaqSDKcdhVuGsz9CWUfnf4DfHDVmddqDDV0mgzdQIJwzKpESC1omXNN1eB8eRPW3sd2aNiPtCv0RX26zNyezAUD0GjDLF00HK6tgBbznhJKqUJrVhmCGm9gQd7nKE/JVbX7l5ozQloS44NuGcREYPqFkkHRS4dfucjTrvh4AfX+jRmavKUWabFQqhCYZIQREF12SGaSKQTJuj/s2OKw4DUhX0s=
  - secure: iZ1wHs7yhnE/ms15aizeWsj6b5zvWA64pzS+uuuLnpCAXFV15S4vybAZAwYOSHlnPpVjO+ocP9js1x72pqjclTHqdkhdIdD0w9biPvRiH9URvsTRPKRGXB9nXJsb+7BFQy/dpsuY/5BPZF5pDPTLkvbcVfOt6kmJd029sHNNfWuIHMTDcPeVqqZuh8KXsyuPuOCc7xoxLiyGAs4JHbBcs7oksTFCdiBfYE9ft1qEJmO/DMcMpNwsLd5Om/smwbIuYosj9bLzSed9MqvZmzeFufL5Tiy6rb9lijbtuMJkCjXYQbEV+UjLi6IW54rSVge++cswUfkofbgwUgFEHBnVIHemnAL2oxqsWr2U6TAifG1nAWc3aF7YhNjxP8egJvIvrk+uvGK6xXafmGhwP7t/FsaAqTfrKR4NnCn5ll8jcuSmuVDqX2uRNtvwsSBCXIMKO2giyKZ27HMQvKIWMFcn4PBshZ/UW1TNP2PHSe6y7dGyUHStGcZ07x3w25ao4ow5dcPY0AMFX5fD1n5ShShMWlmL+4EhclpkGFAsivuhuY1TF0AitR+/IVvbPko3PGYUg0sjO/ShE/omG++aMb8uRkGWKh8oQDw0i1hMxMWp8L+5Zbgrc4bvF7zJUatPRDVg/NOZAXHv10qNQXiKZLDw5lB+kr542ssBb1H8+QhMC6c=
